### ISSUE TITLE
☂️ React Native Compatibility Tracker

### ISSUE THREAD

**Issue by bentobox19** [LavaMoat/docs#1]
This issue tracks the work to make LavaMoat compatible with React Native.

## Tracker

- [X] Proof of Concept Notes
  - https://github.com/LavaMoat/docs/blob/main/react-native-and-ses-lockdown.md
  - https://github.com/LavaMoat/docs/blob/main/rn-ses-archived-notes.md
- [X] Pull Request on MetaMask Mobile Repository
  - https://github.com/MetaMask/metamask-mobile/pull/3794
- [x] Proof of Concept Insights
  - [x] https://github.com/LavaMoat/docs/issues/2
  - [x] https://github.com/LavaMoat/docs/issues/3
  - [x] https://github.com/LavaMoat/docs/issues/4
  - [x] https://github.com/LavaMoat/docs/issues/5
  - [x] https://github.com/LavaMoat/docs/issues/6
  - [x] https://github.com/LavaMoat/docs/issues/7
  - [x] https://github.com/LavaMoat/docs/issues/8
  - [x] https://github.com/LavaMoat/docs/issues/9

--------------------------------------------------------------------------------

## Further Reading

- https://github.com/endojs/endo/issues/661

**Comment by leotm** [comment]
Remaining tracked in
- https://github.com/LavaMoat/docs/issues/12
