### ISSUE TITLE
☂️ React Native Compatibility Tracker 2.0

### ISSUE THREAD

**Issue by leotm** [LavaMoat/docs#12]
- https://github.com/LavaMoat/docs/issues/1 ([ses@0.15.9](https://github.com/endojs/endo/releases/tag/ses%400.15.9)) continued with [ses@0.18.1](https://github.com/endojs/endo/releases/tag/ses%400.18.1) and [beyond](https://github.com/endojs/endo/tags) 🚀

**Priority matrix**
- SES: **module** / **lockdown shim**
- JS engine: **JSC*** / _V8 (debug)_ / **Hermes** / <s>more</s>
- JS transformer: **Babel** / <s>SWC</s>, <s>react-codemod</s>
- JS features: **BigInt** / **Promises** / etc, **libs**
- RN version: <s><=0.66.x</s> / <s>0.66.5* [metamask-mobile](https://github.com/MetaMask/metamask-mobile)</s> / <s>0.69.x*</s> / <s>0.70.x</s> / **0.71.x** [metamask-mobile](https://github.com/MetaMask/metamask-mobile) / 0.72.x / 0.73.x
  - _min: `platform :ios, '11.0'` _0.69+: 12.4__
- RN bundler: **Metro** / <s>Re.Pack</s> / <s>rn-esbuild</s>, bundling / sourcemaps
- RN platform: **Android** / **iOS** / <s>rn-web</s> / <s>rn-macos</s> / <s>rn-windows </s>
- RN _<s>variant*</s>_ mode: **debug** / **release**
- RN arch: **old** / <s>_new**_</s>
- SES integration: entry file / **RN core**

_* undergoing retirement_
_** [3rd party libs](https://github.com/reactwg/react-native-new-architecture/discussions/6) not yet mature, but issues prioritised_

# Tracker
- [x] https://github.com/LavaMoat/docs/issues/10
- [x] https://github.com/LavaMoat/docs/issues/11
  - iOS JSC/V8: Functional RN 0.66.5 app with Promise warnings only 🎉 (no errors seen prev in [ses@0.15.9](https://github.com/endojs/endo/releases/tag/ses%400.15.9))
  - [x] _https://github.com/LavaMoat/docs/issues/13 expected_
  - [x] _https://github.com/LavaMoat/docs/issues/14 expected_
- [x] _https://github.com/LavaMoat/docs/issues/15_
- [x] https://github.com/LavaMoat/docs/issues/16
  - _Prev ses@0.15.9 Promise errors https://github.com/LavaMoat/docs/issues/5_
  - [x] https://github.com/endojs/endo/issues/660
  - - _https://github.com/react-native-community/jsc-android-buildscripts/issues/181 we're no longer using android-jsc but Hermes instead_
  - [x] https://github.com/endojs/endo/pull/1511
- https://github.com/LavaMoat/docs/issues/11
  - we use rn-nodeify in mm-mobile so this isn't an issue
  - but vanilla RN shouldn't need a Node process shim
  - nb: _trusted_ shim valid cases for deps reflect-metadata, pos Sentry
- [x] Create scripts for debug/release Android/iOS building/bundling/running
- [x] QA [RN 0.66.5 + SES 0.18.2patched] bundling and sourcemap gen
  - [x] iOS: debug-mode / release-mode (prod pods) runtime
  - [x] Android: debug-mode / release-mode runtime
  - [x] iOS: Generate and check debug/release bundles with sourcemaps
  - [x] Android: Generate and check debug/release bundles with sourcemaps
  - SES warnings only
- [x] https://github.com/LavaMoat/docs/issues/3
- [x] https://github.com/LavaMoat/docs/issues/5
- [x] [RN 0.71.6+, SES module / lockdown shim, 0.18.1+, Android/iOS, JSC/V8] with Promises
  - [x] iOS JSC: 29 warnings
    - [x] _Promises: `TypeError: Promise constructor's argument is not a function`_
  - [x] _iOS JSC shim: [`TypeError: undefined is not an object (evaluating 'getPrototypeOf(AsyncGeneratorPrototype)')`](https://user-images.githubusercontent.com/1881059/235675024-a0079693-165b-4fdf-8eee-dfc924fa8537.png)_
  - [x] iOS V8: 32 warnings
    - [x] _Promises: `TypeError: Promise constructor's argument is not a function`_
  - [x] _iOS V8 shim: `TypeError: Cannot convert undefined or null to object` debug via Chrome_
  - [x] iOS JSC/V8 BigInt: 1n+2n, BigInt(1) + BigInt(2)
  - [x] Android JSC BigInt: 1n `[SyntaxError: No identifiers allowed directly after numeric literal] x2 no stack x2`, BigInt(1) + BigInt(2) `ReferenceError: Can't find variable: BigInt`
    - [x] https://github.com/MetaMask/metamask-mobile/pull/6221
    - [x] https://github.com/MetaMask/metamask-mobile/pull/6314
  - [x] Android V8 BigInt: 1n+2n, BigInt(1) + BigInt(2)
  - [x] Android JSC: 20 warnings
    - [x] _Promises: [`TypeError: Promise constructor's argument is not a function`](https://user-images.githubusercontent.com/1881059/235670560-3ce01ace-b9bd-4938-9af5-a25eea6b4d36.png)_
  - [x] Android V8: _same as iOS_
  - [x] Android JSC shim: _same as iOS ([stacktrace](https://user-images.githubusercontent.com/1881059/235672688-3b4d1afa-fc61-4b1d-a439-43a48b0bbeca.png))_
  - [x] Android V8 shim: _same as iOS_
- **metamask-mobile** <s>[RN 0.67 support](https://github.com/MetaMask/mobile-planning/issues/663)</s> **[RN 0.71 support](https://github.com/MetaMask/mobile-planning/issues/690)**
  - as seen in (4) past [issues](https://github.com/LavaMoat/docs/issues?q=is%3Aissue+is%3Aopen+label%3Ametamask-mobile+sort%3Aupdated-desc)
  - as seen in https://github.com/MetaMask/metamask-mobile/pull/3794
  - _https://github.com/endojs/endo/issues/699 solved since below_
    - [x] _https://github.com/LavaMoat/docs/issues/4 getPrototypeOf only_
  - [x] **iOS JSC**: UI `TypeError: undefined is not an object (evaluating 'state.engine.backgroundState.NetworkController.network')` w/o polyfillPromise (prev: immediate error, fewer warnings) 22 warnings, 3->6 errors (and remaining libraries)
  - [x] **iOS V8**: (prev UI `TypeError: Cannot read properties of undefined (reading 'network')`), **3->5 errors**, 3 Sentry warnings, SES intrinsics removed warnings below (and remaining libraries)
    - 18-20 warnings (w/o polyfillPromise, prev: immediate error): 4-6 Object, 2 Reflect, 7 %ArrayPrototype%, 2 %StringPrototype%, 1 %RegExpPrototype%, 3 %TypedArrayPrototype%
    - 18 warnings (w polyfillPromise): 7 Promise, 4 %PromisePrototype%; 7 undeletable tolerated (4 Promise.x.prototype, 3 %PromisePrototype%.x.prototype)
    - 2 [errors](https://gist.github.com/leotm/0b2fd9409472a20b5eee24c834f83dcf) stemming from redux-persist
    - `SES_UNHANDLED_REJECTION:` missing Exception error msg
  - RN upgrade from 0.66.5 to 0.71.6
    - [x] https://github.com/MetaMask/metamask-mobile/pull/6119
    - [x] https://github.com/MetaMask/metamask-mobile/pull/6220
  - [x] https://github.com/MetaMask/metamask-mobile/pull/6586
  - _Deprecate JSC support, unless for backward-compat only_
- [x] https://github.com/LavaMoat/docs/issues/17
- [x] Close https://github.com/LavaMoat/docs/issues/1
- _nb: `npx react-native@latest init RN0720RC0 --version 0.72.0-rc.0` now requires Node 16 to init_
- **Hermes support**
  - https://github.com/facebook/hermes/issues/957 not happening anytime soon
  - https://github.com/facebook/hermes/issues/1056 not happening anytime soon
  - [x] https://github.com/endojs/endo/issues/1891 codemod
    - [x] https://github.com/MetaMask/metamask-mobile/pull/8009
    - [x] https://github.com/MetaMask/metamask-mobile/pull/8161
- <s>QA: [RN 0.72.x + SES/lockdown 0.18.x + Android/iOS + Hermes + debug/release + Bundling + Promises]</s>
- [x] https://github.com/MetaMask/metamask-mobile/pull/8033
- [x] https://github.com/reactwg/react-native-releases/discussions/64
  - nb: https://github.com/facebook/react-native/pull/37073
- **Build/compiler time protection**
  - [ ] policy generation (RN android/ios deps aren't within LavaMoat JS ecosystem)
  - [ ] allow-list for RN native deps
  - [ ] Building our RN app under lockdown
  - [ ] Build our RN app under [LavaMoat Node](https://github.com/LavaMoat/LavaMoat/tree/main/packages/node)
- **Runtime protection**
  - [x] <s>Running under lockdown</s> above ^
  - [ ] Runtime protection under [LavaMoat Node](https://github.com/LavaMoat/LavaMoat/tree/main/packages/node)
- [ ] Close https://github.com/endojs/endo/issues/661
- [React Native New Architecture](https://github.com/reactwg/react-native-new-architecture/discussions) support
  - [ ] RN 0.7x.x + npm SES 0.18.x
    - [ ] Add Discussion post
  - [ ] metamask-mobile integration
- Sample/demo repo's
  - [ ] `react-native-lavamoat-lockdown` repo (since this is beyond _/docs_ now) w CI matrix? lavamoat/RN/node vers
  - [ ] migration sample repo like [RNNewArchitectureApp](https://github.com/react-native-community/RNNewArchitectureApp)
- [ ] **Official integration into React Native core?**
  - _After no more warnings [milestone](https://github.com/LavaMoat/docs/milestone/2)_
- [ ] https://github.com/endojs/endo/issues/662
- [ ] https://github.com/LavaMoat/LavaMoat/issues/349
  - nb: https://yarnpkg.com/advanced/lifecycle-scripts
- Bundlers support
  - [x] Metro
  - [ ] Re.Pack (Webpack-based) support
  - [ ] <s>ESBuild support</s>, <s>Not flexible enough atm</s>
    - from sync this morn (9/3/23), maybe viable
- Transformers support
  - [x] Babel
  - [ ] SWC
- Static transformers support
  - [ ] react-codemod
- <s> React Native backward-compat pre-0.66.5</s>
  - _React Native Releases > Releases Support Policy > [which-versions-are-currently-supported](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported)_
- [ ] Expo support ([babel-preset-expo](https://github.com/expo/expo/tree/master/packages/babel-preset-expo))
  - _extends [metro-react-native-babel-preset](https://github.com/facebook/metro/tree/main/packages/metro-react-native-babel-preset)_
- [ ] Further JS engine support
  - On RN New Arch (JSI)
- [x] https://github.com/yarnpkg/berry/issues/3591
- Future-proofing
  - [ ] RN Nightlies
  - [ ] test262.report
  - [ ] [react-native-template-new-architecture](https://github.com/leotm/react-native-template-new-architecture)
- [ ] <s>[endojs/Jessie](https://github.com/endojs/Jessie) for RN</s>
- <s>Cross-platform support</s>
  - [ ] <s>Flutter</s>
  - [ ] <s>KMM</s>

## metamask-mobile

- LogBox.ignoreLogs([...])
- deps (Sentry, eth...)
- e2e (Detox/(Appium))
  - 4.3. Enabling unencrypted traffic for Detox
    > For Detox to work, its native code running on Android device has to be able to connect to the **Node.js host** running tests. It sends an unencrypted HTTP traffic via virtual `localhost` interface, that's why you need to create a new file which adds a couple of exceptions to the security rules.
    > If properly configured, this approach in no way compromises the security settings of your app. For more details, refer to [Android’s security-config guide](https://developer.android.com/training/articles/security-config) and the [dedicated article](https://android-developers.googleblog.com/2016/04/protecting-against-unintentional.html) in the Android developers blog.

## Notes

RN 0.66.5 [types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native/v0.66) ([globals.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/v0.66/globals.d.ts)) (js [global objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects))

**[android-jsc](https://github.com/react-native-community/jsc-android-buildscripts)** ([fbarchive](https://github.com/facebookarchive/android-jsc)) (debug-mode, release-mode)
["jsc-android": "^250231.0.0"](https://github.com/facebook/react-native/blob/0.71-stable/package.json#L126) (WebKitGTK 2.26.1) pre-RN 0.72
`jscFlavor = 'org.webkit:android-jsc:+'` (or `jscFlavor = 'org.webkit:android-jsc-intl:+'`)
pre-release: [v294992.0.0](https://github.com/react-native-community/jsc-android-buildscripts/releases/tag/v294992.0.0) (WebKitGTK 2.36.3) (only `jscFlavor = 'org.webkit:android-jsc-intl:+'`)
_Moved out of [package.json](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/template/package.json) in [0.72-stable](https://github.com/facebook/react-native/commits/0.72-stable?after=2c6edee68e936129644c14736e684a14bd11c55c+34&branch=0.72-stable&qualified_name=refs%2Fheads%2F0.72-stable) [| RN Monorepo | Migrate to package](https://github.com/facebook/react-native/pull/36434)_

**[v8-android](https://github.com/Kudo/v8-android-buildscripts)** (debug-mode: Remote JS Debugging, [opt-in](https://github.com/Kudo/react-native-v8#v8-variants): release-mode)
[v11.110.1](https://github.com/Kudo/v8-android-buildscripts/releases/tag/v11.110.1) (jit/aot, intl/nointl)

[Simplified model of moving parts](https://user-images.githubusercontent.com/1881059/213534843-66efb1d1-1929-4437-ac1b-ea28d7a1ab32.png) (todo: interactive diagram)

**[javascript-environment](https://reactnative.dev/docs/0.66/javascript-environment): RN JS engines (3), transforms (~37), polyfills (11)**

> JavaScriptCore does not use JIT due to the absence of writable executable memory in iOS apps

> When using Chrome debugging, all JavaScript code runs within Chrome itself, communicating with native code via WebSockets. Chrome uses [V8](https://v8.dev/) as its JavaScript engine

RN JS features per engine/platform [table](https://retyui.github.io/react-native-compat-table) (excluding _with_)

**[metro-react-native-babel-preset](https://github.com/facebook/metro/tree/main/packages/metro-react-native-babel-preset) v0.76.0**
_https://github.com/facebook/metro/commit/e5950aeaf0ddb1bf9776ec98509d56f42db2e95d: **\[Breaking]**: Increase minimum Node version from 14 to 16_
[package.json](https://github.com/facebook/metro/blob/main/packages/metro-react-native-babel-preset/package.json): 36 plugins
[main.js](https://github.com/facebook/metro/blob/main/packages/metro-react-native-babel-preset/src/configs/main.js): 23 `extraPlugins.push`
_[babel > packages](https://github.com/babel/babel/tree/main/packages)_

tc39: [terminology](https://github.com/tc39/how-we-work/blob/main/terminology.md) glossary

**Node** (debug via [cli-doctor](https://github.com/react-native-community/cli/tree/main/packages/cli-doctor))
- Metro [bundle](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/node-binary.sh) (+ [sourcemaps](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/compose-source-maps.js#LL28))
- iOS ([Codegen](https://reactnative.dev/docs/next/the-new-architecture/pillars-codegen#running-the-codegen))
  - _https://github.com/facebook/react-native/issues/34872_
  - Xcode: [find-node-for-xcode.sh](https://github.com/facebook/react-native/blob/dc289737a858116bd74fb8b32ef43a8725cb6c51/packages/react-native/scripts/find-node-for-xcode.sh), [react_native_pods_utils/script_phases.sh](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods_utils/script_phases.sh)
- Android
  - Gradle: [android/app/build.gradle](https://github.com/facebook/react-native/blob/12a102b926faa08410cffc688c92968f591740bb/packages/react-native/template/android/app/build.gradle#L26-L28)
- _Jest_
- _Detox_

<img width="583" alt="Screenshot 2023-03-20 at 11 46 50" src="https://user-images.githubusercontent.com/1881059/226331037-db104416-c07d-4445-a064-486e93b14944.png">

<img width="583" alt="Screenshot 2023-03-20 at 11 46 56" src="https://user-images.githubusercontent.com/1881059/226331073-5dee7fd7-d0e8-4eae-a381-cc060b7e71c8.png">

https://drive.google.com/file/d/1mgKxKlpgjm2_KX4TP-G7hUti-JKjR2Xv/view

https://tmikov.blogspot.com/2023/09/how-to-speed-up-micro-benchmark-300x.html

https://www.youtube.com/watch?v=q-xKYA0EO-c

**Join the convo 🌍** 
- https://app.element.io/#/room/#hardenedreactnative:matrix.org
- https://ocapjs.org
